name: "BasicMinestomServer Maven CI"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Set up JDK 17"
        uses: "actions/setup-java@v2"
        with:
          java-version: 17
          distribution: "adopt"
          cache: "maven"
      - name: "Set up Maven"
        uses: "stCarolas/setup-maven@v4.2"
        with:
          maven-version: "3.8.3"

      - name: "Build with Maven"
        run: "mvn clean package"

      - name: "Remove original jar"
        run: "rm -f basic-server/target/original-*.jar"
      - name: "Remove sources jar"
        run: "rm -f basic-server/target/*-sources.jar"
      - name: "Remove javadoc jar"
        run: "rm -f basic-server/target/*-javadoc.jar"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            LICENCE.txt
            basic-server/target/*.jar
